### ISSUE TITLE
R116 - [ADD] add Airdrop-Upgraded

### ISSUE THREAD

**Issue by luizClaudioMendes** [luizClaudioMendes/dayz_project#116]
**Name of the mod**
Airdrop-Upgraded

**Link to the mod**
https://steamcommunity.com/sharedfiles/filedetails/?id=1870524790

**why we should add this mod?**
adds air drops on the map

**Comment by Gfxbyboss** [comment]
OK-BLOCKCHAIN AIRDROP💠
The cryptocurrency exchange

with the most options

OKB offers a fully customizable Bitcoin and cryptocurrency exchange for traders at every level
https://t.me/OKBLOCKCHAIN
